# 문제 2

In [9]:
import numpy as np

arrayA = np.arange(16)
print('arrayA:\n', arrayA)

arrayB = arrayA.reshape(-1,8)
print('arrayB:\n',arrayB)

arrayC = arrayA.reshape(-1,4)
print('arrayC:\n',arrayC)

arrayD = arrayA.reshape(-1,2)
print('arrayD:\n',arrayD)

arrayA:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
arrayB:
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
arrayC:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
arrayD:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


# 문제 3 (못풀었음ㅜㅜ)

In [95]:
import pandas as pd

data = {'이름' : ['아이유', '홍길동', '김단국'],
        '파이썬' : [ 90, 80, 100],
        '수영' : [ 98, 89, 95],
        '인공지능' : [ 95, 95, 100],
        '피아노' : [ 100, 90, 90]
       }

df = pd.DataFrame(data)

print(df.info(), '\n')
print(df.describe(), '\n')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   이름      3 non-null      object
 1   파이썬     3 non-null      int64 
 2   수영      3 non-null      int64 
 3   인공지능    3 non-null      int64 
 4   피아노     3 non-null      int64 
dtypes: int64(4), object(1)
memory usage: 248.0+ bytes
None 

         파이썬         수영        인공지능         피아노
count    3.0   3.000000    3.000000    3.000000
mean    90.0  94.000000   96.666667   93.333333
std     10.0   4.582576    2.886751    5.773503
min     80.0  89.000000   95.000000   90.000000
25%     85.0  92.000000   95.000000   90.000000
50%     90.0  95.000000   95.000000   90.000000
75%     95.0  96.500000   97.500000   95.000000
max    100.0  98.000000  100.000000  100.000000 



# 문제 4

In [41]:
import numpy as np

array = np.array([[[1, 4, 7],
                   [2, 9, 7],
                   [1, 3, 0],
                   [9, 6, 9]],
                  [[2, 3, 4],
                   [3, 4, 5],
                   [0, 1, 2],
                   [6, 7, 8]]])
print('array type:', type(array))
print('array 차원:', array.ndim)
print('array 형태:', array.shape)

array type: <class 'numpy.ndarray'>
array 차원: 3
array 형태: (2, 4, 3)


# 문제 5

In [61]:
import pandas as pd

data = {'파이썬' : [ 90, 80, 100], '수영' : [ 98, 89, 95],
        '인공지능' : [ 95, 95, 100], '피아노' : [ 100, 90, 90]}

df = pd.DataFrame(data, index=['아이유', '홍길동', '김단국'])

# '홍길동' 행 선택
A = df.loc['홍길동']
print(A, '\n')

# '수영' 열 선택
B = df['수영']
print(B, '\n')

# '파이썬', '피아노' 점수 선택
C = df.loc[['아이유', '홍길동', '김단국'], ['파이썬', '피아노']]
print(C, '\n')

# '홍길동'의 '수영'과 '피아노' 점수 선택
D = df.loc['홍길동', ['수영', '피아노']]
print(D, '\n')

파이썬     80
수영      89
인공지능    95
피아노     90
Name: 홍길동, dtype: int64 

아이유    98
홍길동    89
김단국    95
Name: 수영, dtype: int64 

     파이썬  피아노
아이유   90  100
홍길동   80   90
김단국  100   90 

수영     89
피아노    90
Name: 홍길동, dtype: int64 



# 문제 6

In [62]:
import numpy as np

array = np.array([[1,3,5],
                  [2,4,6]])

print(array.sum(axis=0))
print(array.sum(axis=1))
print(array.sum())

[ 3  7 11]
[ 9 12]
21


# 문제 7

In [64]:
import pandas as pd

data = {'파이썬' : [ 90, 80, 100], '수영' : [ 98, 89, 95],
           'AI' : [ 95, 95, 100], '피아노' : [ 100, 90, 90]}

dfA = pd.DataFrame(data, index=['아이유', '홍길동', '김단국'])
dfB = pd.DataFrame(dfA)

# '홍길동' 행 삭제
dfB.drop('홍길동', inplace=True)
dfC = pd.DataFrame(dfB)

# '수영' 열 삭제
dfC.drop('수영', axis=1, inplace=True)

print(dfA)
print()
print(dfB)
print()
print(dfC)

     파이썬  수영   AI  피아노
아이유   90  98   95  100
홍길동   80  89   95   90
김단국  100  95  100   90

     파이썬  수영   AI  피아노
아이유   90  98   95  100
김단국  100  95  100   90

     파이썬   AI  피아노
아이유   90   95  100
김단국  100  100   90


# 문제 8

In [67]:
import pandas as pd

data = {'Kim' : 30, 'Lee' : 40, 'Park' : 55}

sr = pd.Series(data)

print(type(sr))
print()
print(sr)
print("'Lee'의 값 :", sr['Lee'])

<class 'pandas.core.series.Series'>

Kim     30
Lee     40
Park    55
dtype: int64
'Lee'의 값 : 40


# 문제 9 (못 풀었음ㅜㅜ)

In [91]:
import numpy as np

arrayA = np.array([4,8,17,29,44,50,62,63,74,81])
print('arrayA:\n', arrayA)

arrayB = [50 62 63 74 81]
print('arrayB:\n', arrayB)

arrayC = [29 50 74]
print('arrayC:\n', arrayC)

arrayD = [50 62 63 74 81]

# arrayA의 원소중에 50 이상인 값만 필터링
print('arrayD:\n', arrayD)

SyntaxError: invalid syntax (<ipython-input-91-d3a13dd59656>, line 6)

# 문제 10

In [92]:
def max2(m, n):
     if m > n :
        return m
    
     else :
        return n

def min2(m, n):
     if m < n :   
        return m

     else :
        return n

           

print('100과 200중 큰 수는 :', max2(100, 200))
print('100과 200중 작은 수는 :', min2(100, 200))

100과 200중 큰 수는 : 200
100과 200중 작은 수는 : 100


# 문제 11

In [94]:
def get_sum(start, end):
    sum = 0
    for i in range(start+1, end):
          sum += i
    return sum

a = get_sum(1, 4)
print(a)

5


In [1]:
import pandas as pd

# read_excel()함수로 데이터프레임 변환
df = pd.read_excel('./test.xlsx')        # header=0 (default 옵션)
df

Unnamed: 0    a   b   c   d    e   f   g   h    i  ...  q    r    s    t  \
0      1.txt  157  32  70  68  244  36  30  92  147  ...  0  121  143  155   
1      2.txt  203  23  59  88  309  62  56  97  159  ...  7  154  146  207   
2      3.txt  137  25  54  60  175  35  29  82  149  ...  1   79  123  136   

    u   v   w   x   y  z  
0  44  15  31   6  21  4  
1  51  36  32  10  36  2  
2  36  29  24   4  25  1  

[3 rows x 27 columns]